## Description

1. ***Invoice:*** Номер счета. 6-значный целочисленный номер, уникально присваиваемый каждой транзакции. Если этот код начинается с английской буквы «c», это означает аннулирование. 
2. ***StockCode:*** Код товара (наименования). 5-значный целочисленный номер, уникально присваиваемый каждому отдельному товару. 
3. ***Description:*** Название товара (наименования). 
4. ***Quantity:*** Количество каждого товара (наименования) в одной транзакции. 
5. ***InvoiceDate:*** Дата и время выставления счета. День и время создания транзакции. 
6. ***UnitPrice:*** Цена за единицу. Цена товара за единицу в фунтах стерлингов (£). 
7. ***CustomerID:*** Номер клиента. 5-значный целочисленный номер, уникально присваиваемый каждому клиенту. 
8. ***Country:*** Название страны. Название страны, в которой проживает клиент.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/online_retail_II.csv")
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [12]:
df["Description"][1345]

'PINK PAISLEY CUSHION COVER '

In [4]:
df.shape

(1067371, 8)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  object
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 65.1+ MB

In [6]:
df.describe()

           Quantity         Price    Customer ID
count  1.067371e+06  1.067371e+06  824364.000000
mean   9.938898e+00  4.649388e+00   15324.638504
std    1.727058e+02  1.235531e+02    1697.464450
min   -8.099500e+04 -5.359436e+04   12346.000000
25%    1.000000e+00  1.250000e+00   13975.000000
50%    3.000000e+00  2.100000e+00   15255.000000
75%    1.000000e+01  4.150000e+00   16797.000000
max    8.099500e+04  3.897000e+04   18287.000000